import type { Analysis, DetectedClaim, TechniqueFinding } from "@prisma/client";
import type { PhaseMarker } from "@/lib/rhetoric/types";

type AnalysisExport = Analysis & {
  findings: TechniqueFinding[];
  claims: DetectedClaim[];
};

const techniqueLabels: Record<string, string> = {
  GISH_GALLOP: "Gish Gallop",
  FIREHOSE: "Firehosing",
  CORRELATION_CAUSATION: "Correlation → Causation",
  STATISTICAL_DISTORTION: "Statistical Distortion",
  STRAWMAN: "Strawman",
  UNSUPPORTED_LEAP: "Unsupported Leap",
  PREEMPTIVE_CLOSURE: "Preemptive Closure",
};

export function buildMarkdownReport(
  analysis: AnalysisExport,
  phases: PhaseMarker[] = [],
): string {
  const lines: string[] = [
    "# Rhetoric Analysis Report",
    "",
    `**Video:** ${analysis.videoUrl}`,
    `**Video ID:** ${analysis.videoId}`,
    `**Status:** ${analysis.status}`,
    `**Analyzed:** ${analysis.createdAt.toISOString()}`,
    "",
  ];

  if (analysis.summary) {
    lines.push("## Summary", "", analysis.summary, "");
  }

  if (analysis.overallScore != null) {
    lines.push(`**Overall manipulation signal:** ${Math.round(analysis.overallScore)}/100`, "");
  }

  if (phases.length > 0) {
    lines.push("## Gish Gallop Phase Timeline", "");
    for (const phase of phases) {
      lines.push(
        `### ${phase.phase} — [${phase.timestamp}]`,
        "",
        phase.description,
        "",
        phase.trigger ? `_Trigger: "${phase.trigger}" (${Math.round(phase.confidence * 100)}% confidence)_` : "",
        "",
      );
    }
  }

  if (analysis.findings.length > 0) {
    lines.push("## Technique Scores", "");
    for (const finding of analysis.findings) {
      lines.push(
        `### ${finding.title} — ${Math.round(finding.score)}/100 (${finding.severity})`,
        "",
        finding.summary,
        "",
      );
    }
  }

  if (analysis.claims.length > 0) {
    lines.push("## Flagged Claims", "");
    for (const claim of analysis.claims) {
      lines.push(
        `### [${claim.timestamp ?? "?"}] ${claim.verdict}`,
        "",
        `**Technique:** ${techniqueLabels[claim.technique] ?? claim.technique}`,
        `**Excerpt:** ${claim.excerpt}`,
        `**Confidence:** ${Math.round(claim.confidence * 100)}%`,
        "",
        `> ${claim.text}`,
        "",
        claim.reasoning,
        "",
        "---",
        "",
      );
    }
  }

  lines.push(
    "_Generated by Debate Fact Checker. Heuristic analysis only — verify claims against primary sources._",
  );

  return lines.join("\n");
}
